os: osx
osx_image: xcode15.3
language: swift
xcode_project: OmronLibrarySample.xcodeproj
xcode_scheme: OmronLibrarySample
xcode_destination: platform=iOS Simulator,name=iPhone 15 Plus,OS=17.4

env:
  global:
    - LANG=en_US.UTF-8

# Decrypt the Firebase service account key
before_script:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in firebase-key.json.enc -out firebase-key.json -d

# Build and sign the app
script:
  - xcodebuild clean archive \
    -project OmronLibrarySample.xcodeproj \
    -scheme OmronLibrarySample \
    -archivePath build/OmronLibrarySample.xcarchive \
    CODE_SIGN_IDENTITY="iPhone Distribution: AliveCor, Inc. (Ent)" \
    PROVISIONING_PROFILE_SPECIFIER="OmronConnect_Library_sample"

  # Export the .ipa
  - xcodebuild -exportArchive \
    -archivePath build/OmronLibrarySample.xcarchive \
    -exportPath build \
    -exportOptionsPlist exportOptions.plist

after_success:
  # Install Firebase CLI
  - npm install -g firebase-tools

  # Authenticate Firebase CLI with the service account
  - firebase login:ci --no-localhost --token "1//01P2UEtGIHx4DCgYIARAAGAESNwF-L9Ir71hM5OCXkR449Y6SzxY93up0KBJ697BTaqPFr3ktMMQLDTfbkM4bCOdNDa-eYzpEJ4k"

  # Upload .ipa to Firebase App Distribution
  - firebase appdistribution:distribute build/YourApp.ipa \
    --app "1:547303731110:ios:5d52ff2b643f222aada967" \
    --token "1//01P2UEtGIHx4DCgYIARAAGAESNwF-L9Ir71hM5OCXkR449Y6SzxY93up0KBJ697BTaqPFr3ktMMQLDTfbkM4bCOdNDa-eYzpEJ4k" \
    --groups "qa" \
    --release-notes "New build from Travis CI"
